POST http://localhost:5500/api/item
Content-Type: application/json

{
"item": "Task 2",
"createdDate": "2023-11-08",
"date": "2023-11-09",
"priority" : "low",
"completed": false,
"notes": "asdasd",
"category": "Work",
"notification": 0,
"userEmail": "test@example.com"
}


###

GET http://localhost:5500/api/user/test@example.com/tasks
Content-Type: application/json


###

PUT http://localhost:5500/api/item/654c69390f758457059ec17a
Content-Type: application/json

{
"item": "Updates this!!"
}


###
DELETE http://localhost:5500/api/item/654c69390f758457059ec17a
Content-Type: application/json
